# Generated by Django 5.0.2 on 2024-02-27 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
      #  migrations.CreateModel(
       #     name='Fiszka',
        #    fields=[
         #       ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
          #      ('character', models.TextField()),
           #     ('pinyin', models.TextField()),
            #    ('definition', models.TextField()),
             #   ('difficulti', models.FloatField()),
            #],
        #),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('yt_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('transcript', models.TextField()),
                ('hsk_dict', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('up_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.videos')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('fiszka_id', models.AutoField(primary_key=True, serialize=False)),
                ('character', models.CharField(max_length=50)),
                ('pin_yin', models.CharField(max_length=50)),
                ('definition', models.TextField()),
                ('sentence', models.TextField()),
                ('second_in_video', models.IntegerField()),
                ('duration_time_in_video', models.IntegerField()),
                ('EF', models.FloatField()),
                ('n', models.IntegerField()),
                ('interval', models.IntegerField()),
                ('last_display_date', models.DateField()),
                ('next_display_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.videos')),
            ],
        ),
    ]
