# Generated by Django 5.0.2 on 2024-02-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fiszka_videos_userprogress_flashcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='video',
            new_name='video_id',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='duration_time_in_video',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='last_display_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='next_display_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='hsk_dict',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
