# Generated by Django 5.0.1 on 2024-03-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_fiszka_alter_flashcard_last_display_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='interval',
            field=models.TextField(),
        ),
    ]
