# Generated by Django 5.0.1 on 2024-03-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_flashcard_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_fiszka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pytanie', models.TextField(blank=True, null=True)),
                ('odpowiedz', models.TextField(blank=True, null=True)),
                ('test', models.TextField(blank=True, null=True)),
            ],
        ),
        #migrations.RemoveField(
        #    model_name='fiszka',
        #    name='difficulti',
        #),
        #migrations.AddField(
        #    model_name='fiszka',
        #    name='odpowiedz',
        #    field=models.TextField(blank=True, null=True),
        #),
        #migrations.AddField(
        #    model_name='fiszka',
        #    name='pytanie',
        #    field=models.TextField(blank=True, null=True),
        #),
    ]
