# Generated by Django 5.0.1 on 2024-03-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_api_fiszka_remove_fiszka_difficulti_fiszka_odpowiedz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiszka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pytanie', models.TextField(blank=True, null=True)),
                ('odpowiedz', models.TextField(blank=True, null=True)),
                ('character', models.TextField()),
                ('pinyin', models.TextField()),
                ('definition', models.TextField()),
            ],
        ),
    ]
