# Generated by Django 5.0.4 on 2024-04-16 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fiszka'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateTimeField()),
                ('energy_consumption', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='api_fiszka',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Fiszka',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='video',
        ),
        migrations.AddField(
            model_name='measurement',
            name='user_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userapplication'),
        ),
        migrations.DeleteModel(
            name='Flashcard',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
